### ISSUE TITLE
CSS for generated HTML files

### ISSUE THREAD

**Issue by igrep** [haskell-jp/slack-log#19]
Related: https://github.com/haskell-jp/slack-log/issues/13
Address after merging https://github.com/haskell-jp/slack-log/pull/18

**Comment by igrep** [comment]
FYI.
https://twitter.com/myuon_myon/status/1150314268249616386 and the referred CSS theme: https://semantic-ui.com/views/feed.html

**Comment by mizunashi-mana** [comment]
#33 で解決したので，閉じます
