### ISSUE TITLE
Truncate messages in index.html

### ISSUE THREAD

**Issue by igrep** [haskell-jp/slack-log#26]
In [index.html](https://haskell.jp/slack-log/), the first message of every page of every channel is listed.
But some of the messages are too long to show in index.html.

**Comment by nakaji-dayo** [comment]
@igrep こちら方針良いのか悩んでいて相談させてください。

SlackMessageTextのパース後の構造に対して処理する必要が有り、slack-webに手を入れて対応することになると考えていて、少々大事かもと思っています。
（パース前後の文字列を単純に丸めるとhtmlとして壊れる。または重複して自前でパースすることになり筋が悪い）

もし考えがあれば教えて頂きたいです。

**Comment by igrep** [comment]
おおー、すみません、想定していませんでした 💦 

いずれにしても、あくまでindex.htmlに書く「概要」程度のものなので、厳密にHTMLとして表示する必要はないだろう、という認識です。
なので、`SlackMessageText`のままで何文字かtruncateして、その状態で`messageToHtml`を呼ぶ、というのでいかがでしょうか？
完全なやり方ではないですが実際のところそれで十分なんじゃないか、という認識です。
あるいは`messageToHtml`もしないでそのまま表示するのでもよいです。
URLが中途半端に切れてもクリッカブルにならないのでこの方が安全かも。

再生成に少し時間がかかるので面倒ですが、両方試してみていただけるとありがたいです。

**Comment by nakaji-dayo** [comment]
ありがとうございます！試してみます！

**Comment by nakaji-dayo** [comment]
おっと、まだ試してはないですが、

> SlackMessageTextのままで何文字かtruncateして、その状態でmessageToHtmlを呼ぶ、というのでいかがでしょうか？

messageToHtmlの構文にはhtmlでescapeが必要な文字も入っていて、messageToHtmlはSlackMessaeTextが不完全なことは想定していないので、パース前にtruncateし構文を壊すと、html的に壊れることが有ります（リンク表記`<url>`が切られると、htmlが開きっぱなし等）

> あるいはmessageToHtmlもしないでそのまま表示するのでもよいです。
同じく、html escapeが必要です。

あくまで概要、という意味では、escapeするのが良さそうかとは思いました。
（重複してパースすると近いかもしれないが

**Comment by igrep** [comment]
> あくまで概要、という意味では、escapeするのが良さそうかとは思いました。

確かに。生のmarkdownをそのままplain textとして表示するような感じ（要するにHTML escapeするだけ）でお願いします！
