### ISSUE TITLE
HTML の属性の型表記について

### ISSUE THREAD

**Issue by mizunashi-mana** [haskell-jp/slack-log#32]
Html モジュールで，曖昧な型を避ける為ところどころに文字列リテラルに対して Text の型注釈が書いてありますが，これについて2点質問があります．

* なぜ OverloadedStrings 拡張を使ってるのでしょうか？
* 公式は，[String 型を推奨してるように見える](https://github.com/knupfer/type-of-html#performance) のですが，Text 型を使用している理由は何かあるのでしょうか？

**Comment by igrep** [comment]
そんなに深い理由はなく、純粋に一般論としてTextを使った方がいいだろうと思ってTextにしていました。多分slack-webが提供している型にもTextが使われているから、というのもあるのではないかと（この点は詳しく見てませんが）。

- OverloadedStringsを使っているのは当然Textを使っていたためです。

> 公式は，String 型を推奨してるように見える のですが，Text 型を使用している理由は何かあるのでしょうか？

ものすごく斜め読みした限り特にStringを推奨しているようには見えなかったのですがどうしてでしょうか。

例でOverloadedStringsを使ってなかったから、ですかね？
まぁ確かに逐一型注釈をするのは面倒だと感じてはいたので、Stringに寄せるのは確かにアリだと思います。

**Comment by mizunashi-mana** [comment]
リンク先に文字列リテラルは GHC の最適化により ASCII の範囲に収まるようであれば word8 配列表現で収まるようにしてくれ、utf8 エンコードしないので、その場合に効率がよくなるよう設計してる的なことが書かれてあるように見えます(ちゃんと読めてないですが)

実際に、HTML.Convert モジュールにはそのための rewrite rule が書かれてるみたいですね
