### ISSUE TITLE
JSONの出力順を整える

### ISSUE THREAD

**Issue by igrep** [haskell-jp/slack-log#4]
既存のダンプされたファイルはどうやら時刻の降順（新しいメッセージが先頭にでてくる）になっているらしいので、既存のファイルを逆順に書き換えつつ、保存するアプリケーションについても、保存する時点で逆になるよう書き換える。1コミットでやりたいね。

**Comment by matsubara0507** [comment]
げ、json のパターンいくつかあるのか。。。だるいw

**Comment by igrep** [comment]
そうか、 https://github.com/haskell-jp/slack-log/issues/1 のタスクが残っているのか... ちょっとやってみるわ

**Comment by matsubara0507** [comment]
いややっちゃいます。ついでに。

**Comment by igrep** [comment]
お、じゃぁ今やったところをPRします。

**Comment by matsubara0507** [comment]
全部書き換える script 書いてたんで、ついでにフォーマットも整えるようにしようかと思ってまして。

**Comment by igrep** [comment]
なるほど。。。じゃぁ中途半端に手出ししない方がよかったですね。。。申し訳ない。
https://github.com/haskell-jp/slack-log/pull/6 はcloseします。
