### ISSUE TITLE
slack のチャンネル系 Web API が非推奨になります

### ISSUE THREAD

**Issue by matsubara0507** [haskell-jp/slack-log#42]
ref https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api

チャンネルの情報を取得するのにパブリックチャンネルだと `channels.*` を、プライベートチャンネルだと `groups.*` を使ってましたが、これを統一した [`conversations.*`](https://api.slack.com/docs/conversations-api) ができました。
[以下のスケジュール](https://api.slack.com/changelog/future)で古い API は使えなくなります：

- 2020/6/10: この日以降に作った Slack Apps では古い API を利用できなくなる
- 2021/2/24: 既存の Slack Apps でも古い API を利用できなくなる（もともと 2020/11 だったけど延長された）

haskell-jp/slack-log は slack-web を介して古い API を利用しているので置き換えた方がいいです。
問題はどうやってこれに対応するか

1. slack-web に conversations api に対応したパッチを投げる
2. conversations api を自作する

前に調べた限り conversations api に対応した slack haskell client はない（[僕が自作してるやつ](https://github.com/matsubara0507/slackell)は対応いてるけど、extensible 依存なので。。。）ので、上のどっちかかなぁって思ってます。

**Comment by igrep** [comment]
> slack-web に conversations api に対応したパッチを投げる

もちろんそれはちゃんと貢献しましょう。
問題はデータ構造とかが変わってないかが心配です。スレッドを正しく表現できるとなると結構大規模な修正と決断が必要になるので...

**Comment by matsubara0507** [comment]
はい。実はそこなんです。
パブリックチャンネル・プライベートチャンネル・DM・複数人DMの4種類を統合した結果、4種類の結果が混ざって返ってきます。
混ざってというのはデータ構造がバラバラという意味です。

パブリック・プライベートチャンネルに違いはないはずなんですけど、DM系とは全然違うんですよね。。。
Slack 側もそれを認識して、追々直したいとは書いてあるんですけど、現状ダメです。

**Comment by matsubara0507** [comment]
混ざってるので僕はほぼ Maybe なデータ構造を作りました笑
https://github.com/matsubara0507/slackell/blob/6c8aeefa4c44be4f70537bb9879756d53b705c94/src/Web/Slack/Type.hs#L56-L84

さすがにこれだと不便なので、チャンネル系・DM系で分けた型も作って、それぞれしか返ってこない関数も作ったけど。

**Comment by igrep** [comment]
slack-webにもissueを作っておきました https://github.com/jpvillaisaza/slack-web/issues/82

**Comment by igrep** [comment]
📝 進捗メモ: https://editor.swagger.io/ に https://github.com/slackapi/slack-api-specs/blob/master/web-api/slack_web_openapi_v2.json を入力することで、試しにconversations.listを実行して、conversions.listの仕様を把握しました。

**Comment by matsubara0507** [comment]
slackell で採用した方法を雑に実装してみた
https://github.com/matsubara0507/slack-web/compare/master...conversations

```haskell
-- ghci 
import qualified Web.Slack as Slack
import qualified Web.Slack.Conversation as Conversation 
import qualified Web.Slack.Channel as Channel
import qualified Web.Slack.Group as Group
import qualified Web.Slack.Im as Im
import Control.Monad.Reader
import Data.Maybe (mapMaybe)
:set -XOverloadedStrings

> slackConfig <- Slack.mkSlackConfig "xxx"
> Right resp <- flip runReaderT slackConfig (Slack.conversationsList $ Conversation.mkListReq { Conversation.listReqTypes = Just "public_channel,private_channel,im" })
> length $ Conversation.listRspChannels resp
50
> length $ mapMaybe Channel.fromConversation $ Conversation.listRspChannels resp
47
> length $ mapMaybe Group.fromConversation $ Conversation.listRspChannels resp
1
> length $ mapMaybe Im.fromConversation $ Conversation.listRspChannels resp
2
```

**Comment by igrep** [comment]
今日はいいニュースと悪いニュースがある。

🎉 いいニュース: Pull request送りました。 https://github.com/jpvillaisaza/slack-web/pull/83

😩 悪いニュース: `channels.history`と違って`conversations.history`はスレッドへのリプライをレスポンスに含めてくれないらしい... なので https://api.slack.com/methods/conversations.replies を別途実装してうまいこと組み込む必要がある。データ構造や処理も考え直さなくては...。 😰

**Comment by igrep** [comment]
まぁいい機会なんでちゃんとスレッドをスレッドらしく表示する機能を実装すればいいんだけど...
さてどうやろうか... 😥

**Comment by igrep** [comment]
実装メモ: 1回の実行ではスレッドのすべてのリプライを取り出せるわけではない（実行した後に新しいリプライが追加される可能性がある）ので、「何日分前のスレッドを確認するか」設定できるようにする必要が

**Comment by igrep** [comment]
やっとここまで来たで... 😩 
https://github.com/jpvillaisaza/slack-web/pull/84

**Comment by igrep** [comment]
今後は https://github.com/haskell-jp/slack-log/tree/fix-42 で開発します。
