### ISSUE TITLE
searchThreadsAppendedSince の結果がOSによって異なる

### ISSUE THREAD

**Issue by matsubara0507** [haskell-jp/slack-log#52]
https://github.com/haskell-jp/slack-log/actions/runs/699846903 で落ちている原因について調査しました。

原因は `System.Directory.listDirectory` で返ってくるファイル名の順番が OS によって異なるからです。

https://github.com/haskell-jp/slack-log/blob/71eba0b95d0b762c217212e8757ddca22b7ccbe8/src/SlackLog/Replies.hs#L53-L57

試しに（雑に）、`print` してみたところ
- Windows では `["2.json","2","1.json","1"]` (GitHub Actions 上)
- Ubuntu では `["1.json","2","2.json","1"]` (GitHub Actions 上)
- Mac では `["1","1.json","2.json","2"]` (手元)

でした（参照： [GitHub Actions の結果](https://github.com/matsubara0507/slack-log/pull/1/checks?check_run_id=2229173244)）。

とりあえず、`System.Directory.listDirectory` した後にソートすれば良いと思います。

一つ不可解なのは[この処理を特にいじってないタイミング](https://github.com/haskell-jp/slack-log/commit/40ab50fa0b36147c8f9115abc6d8757f8c8748cc)から落ちるようになったことです。

あと、もっと根源的なところ（なんでOSによって結果が異なるのか）雑に調べた感じではわかりませんでした。

**Comment by igrep** [comment]
特にお願いもしてないのにわざわざありがとう！ 🙇
