### ISSUE TITLE
ページ番号が正しく割り当てられていない・「Previous」というリンクの参照先がおかしい

### ISSUE THREAD

**Issue by igrep** [haskell-jp/slack-log#54]
https://haskell.jp/slack-log/ を今見ると、なぜかあるときからページ番号が正しく振られておらず、同じページが2ページずつ続いている。スクショの例はrandomチャンネルだけど、ざっと見たところbeginnersチャンネルでも同様の現象が観測された。

また、問題が起きているページを開くと「Previous」というリンクの参照先が自分自身（例えば[randomチャンネルの87ページ目](https://haskell.jp/slack-log/html/C4M4TT8JJ/87.html)だと同じく87ページ目）を差してしまっていて、前のページに進めない。恐らく前者と根っこは同じ問題じゃないかと思われる。

![image](https://user-images.githubusercontent.com/227057/126759669-bb7d53e1-3aeb-4796-87bc-ec5671d62aed.png)

**Comment by igrep** [comment]
弱ったな、ざっとコミットログを見ても心当たりがない。その時期って別のリポジトリーでConversation APIへの対応をしてた時期だから触ってないはずなのに。Conversation API自体のせいじゃないことを祈る...

**Comment by matsubara0507** [comment]
ざっとコード読んだ感じ、原因はここですね

https://github.com/haskell-jp/slack-log/blob/324e4bc95099b6cc3441c5231b78e8070c6c764d/src/SlackLog/Html.hs#L63-L64

ダブってるページ番号の場合（例えば、random の場合は 86-91）は、`[ページ番号].json` の他にそのページ番号のディレクトリがありますね。
それらが `Dir.listDirectory` で引かれてダブってるようです（以降の処理で、`.json` じゃないと弾くみたいな処理はなさそうでした）。

確か、そのページ番号のディレクトリは Conversation API がスレッドを個別に引かなきゃいけない関係で用意したものではないですっけ？なので時期的にもあってそうですね。

**Comment by matsubara0507** [comment]
ちなみに、Previous の方は、ちゃんと調べてませんが、例えば 90, 91, 91 って存在してた場合：

1. 90 が Previous な 91.html が作られる
2. 91 が Previous な 91.html が作られる
3. (2) は (1) を上書き保存する

で、結果として Previous が自分自身のやつだけ残る的な感じかなーってエスパーしました笑

**Comment by igrep** [comment]
> 確か、そのページ番号のディレクトリは Conversation API がスレッドを個別に引かなきゃいけない関係で用意したものではないですっけ？なので時期的にもあってそうですね。

💡 それだ！Conversation APIというか、リプライを保存するためにディレクトリーを一つ増やした結果そうなってしまった、と！

**Comment by matsubara0507** [comment]
ですです。
なんで、どっかに `.json` のみ filter するような処理を挟めば治るかと

**Comment by igrep** [comment]
🆗 今対応中の https://github.com/haskell-jp/slack-log/issues/20 と一緒に対応します。 https://github.com/haskell-jp/slack-log/issues/20 はまさにそのHtml.hsを大幅にいじっているので

**Comment by igrep** [comment]
こちらも https://github.com/haskell-jp/slack-log/pull/55 によって直ってます！
![image](https://user-images.githubusercontent.com/227057/127158594-4d02c276-f8b8-40a6-a6c1-bb90d140cc42.png)
